# Generated by Django 5.0.4 on 2024-05-04 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Enter the 16-digit card number', max_length=16)),
                ('cardholder_name', models.CharField(help_text="Enter the cardholder's name", max_length=100)),
                ('expiry_date', models.DateField(help_text='Enter the card expiry date (MM/YY)')),
                ('cvv', models.CharField(help_text='Enter the 3-digit CVV number', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
