# Generated by Django 5.0.4 on 2024-05-19 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the currency (e.g., USD, EUR, BTC)', max_length=50, unique=True)),
                ('symbol', models.CharField(help_text='Enter the symbol of the currency (e.g., $, €, ฿)', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='Enter the exchange rate relative to a base currency (e.g., 1 USD)', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(help_text='The user who owns this wallet', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='The amount of this currency in the wallet', max_digits=20)),
                ('currency', models.ForeignKey(help_text='The type of currency in this wallet', on_delete=django.db.models.deletion.CASCADE, to='api.currency')),
                ('wallet', models.ForeignKey(help_text='The wallet that this currency belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='api.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'currency')},
            },
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
