# Generated by Django 5.0.4 on 2024-05-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_currency_conversion_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='conversion_rate',
        ),
    ]
