# Generated by Django 5.0.4 on 2024-05-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_wallet_eth_address_wallet_eth_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_token',
            field=models.BooleanField(default=False),
        ),
    ]
